# =============================================================================
# SERVICE ACCOUNT - Identity for Pods
# =============================================================================
# A ServiceAccount provides an identity for pods running in Kubernetes.
#
# WHAT IS A SERVICE ACCOUNT?
# --------------------------
# Think of it like an "employee badge" for your pods:
# - Humans use usernames to authenticate
# - Pods use ServiceAccounts to authenticate
#
# WHY DO WE NEED THIS?
# --------------------
# 1. API Access: Pods may need to call Kubernetes API (list pods, read secrets)
# 2. RBAC Control: Different pods can have different permissions
# 3. Pod Security Policies: PSP requires pods to run as a specific ServiceAccount
#
# THIS FILE IS CONDITIONAL:
# -------------------------
# Only created if psp.enabled=true in values.yaml
# Pod Security Policies (PSP) are deprecated, so this is rarely needed now
#
# HOW IT WORKS:
# -------------
# 1. ServiceAccount is created in the namespace
# 2. ClusterRole defines what actions are allowed
# 3. ClusterRoleBinding connects the ServiceAccount to the ClusterRole
# 4. Pods reference the ServiceAccount to get those permissions
# =============================================================================

# CONDITIONAL: Only create this resource if PSP is enabled
{{ if .Values.psp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  # Name of the service account - referenced by pods
  name: robot-shop
  # Namespace where this service account exists
  namespace: robot-shop
{{ end }}
